---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: requirements-txt-fixer

  - repo: https://github.com/codespell-project/codespell.git
    rev: v2.1.0
    hooks:
      - id: codespell
        args: [-w]
        files: ^.*\.(md|yaml|yml|sh)$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      # Otherwise will fail on commit-msg hook
      - id: prettier
        stages: [commit]
        exclude: Pipfile.lock

  # Security
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.5.3
    hooks:
      - id: gitleaks
